name:                blockheaders-dl
version:             0.1.0.0
github:              "gtklocker/blockheaders-dl"
license:             BSD3
author:              "Kostis Karantias"
maintainer:          "kkarantias@gmail.com"
copyright:           "2019 Kostis Karantias"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gtklocker/blockheaders-dl#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger
- mtl
- aeson
- conduit-extra
- text
- time
- unliftio
- json-rpc == 1.0.0
- scientific

library:
  source-dirs: src

executables:
  blockheaders-dl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockheaders-dl

tests:
  blockheaders-dl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockheaders-dl
